# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CarrierPigeon' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CarrierPigeon

  pod 'CYLTabBarController'
  pod 'Bugly'
  pod 'XHLaunchAd'
  
  
  target 'CarrierPigeonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CarrierPigeonUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
